SUMMARY: Partial port to SIERRA Pathscale 3.0 compiler
BUGS: 4017

CHECKLIST:

1) Did you add any source or other files needed for building, testing,
   or documentation? No

2) Did you update or change the build system (other than just adding
   source files)? No

3) Did you do a cvs update *very* recently before rebuilding and
   retesting? Yes

4) If justified, did you type 'make partial-clean' and then rebuild all
   libraries and executables with 'make everything'? No, I am using the
   SIERRA bjam system but I did build several files.  However, the entire
   g++ 4.2.4 BJAM build of Aria + Trilinos dev release build passed

5) Did you rerun the test suite on at least the packages that you
   changed (rerunning the entire Trlinos test suite on all affected
   packages is *strongly* recommended)? No, the build does not even work
   yet

COMMENTS:

Here I am just making a small change to the default implementations of
Teuchos::TypeNameTraits::concreateName(...) for the pathscdale 3.0 compiler on
the SCICO LAN Linux machine sais503.  Without this change, the compiler error shown at:

https://esc.sandia.gov/~rabartl/aria_trilinos_tests/2008-08-03-02-08/aria_tridev_release_desktop_pathscale/build_sierra_tridev_release_desktop_pathscale.2008-08-03-02-08.out

was:

-------------------------------------------------------------------

/var/scratch2/rabartl/PROJECTS/nightly-porting-tests/Aria_Trilinos/sierra_tri_release/Trilinos/dev/flat_headers/Teuchos_TypeNameTraits.hpp: In instantiation of `Teuchos::TypeNameTraits<int ()(ML_Smoother*, int, double*, int, double*)>':
/var/scratch2/rabartl/PROJECTS/nightly-porting-tests/Aria_Trilinos/sierra_tri_release/Trilinos/dev/flat_headers/Teuchos_TypeNameTraits.hpp:118:   instantiated from `static std::string Teuchos::TypeNameTraits<T*>::name() [with T = int ()(ML_Smoother*, int, double*, int, double*)]'
/var/scratch2/rabartl/PROJECTS/nightly-porting-tests/Aria_Trilinos/sierra_tri_release/Trilinos/dev/flat_headers/Teuchos_any.hpp:163:   instantiated from `std::string Teuchos::any::holder<ValueType>::typeName() const [with ValueType = int (*)(ML_Smoother*, int, double*, int, double*)]'
/usr/lib/gcc/x86_64-redhat-linux/3.4.5/../../../../include/c++/3.4.5/bits/cpp_type_traits.h:337:   instantiated from here
/var/scratch2/rabartl/PROJECTS/nightly-porting-tests/Aria_Trilinos/sierra_tri_release/Trilinos/dev/flat_headers/Teuchos_TypeNameTraits.hpp:91: error: `
   const' qualifiers cannot be applied to `int ()(ML_Smoother*, int, double*,
   int, double*)'
gmake: *** [/var/scratch2/rabartl/SierraLocalNightlyPortingTestsBaseDir/sierra_tri_release/rebuild/SierraBuilds.trilinos_dev.trilinos_dev/equationsolver/votd/pathscale-3.0/release/address-model-32/architecture-x86/mpi-mpich/Solv_NOX_Epetra.o] Error 1

-------------------------------------------------------------------

To fix this error, here is the diff:

-------------------------------------------------------------------

RCS file: /space/CVS/Trilinos/packages/teuchos/src/Teuchos_TypeNameTraits.hpp,v
retrieving revision 1.9
diff -u -r1.9 Teuchos_TypeNameTraits.hpp
--- packages/teuchos/src/Teuchos_TypeNameTraits.hpp     2 Aug 2008 04:23:13 -0000       1.9
+++ packages/teuchos/src/Teuchos_TypeNameTraits.hpp     3 Aug 2008 21:55:49 -0000
@@ -87,7 +87,7 @@
       return demangleName(typeid(T).name());
     }
   /** \brief . */
-  static std::string concreteName( const T& t )
+  static std::string concreteName( T& t )
     {
       return demangleName(typeid(t).name());
     }
@@ -116,7 +116,7 @@
 public:
   typedef T* T_ptr;
   static std::string name() { return TypeNameTraits<T>::name() + "*"; }
-  static std::string concreteName( const T_ptr& t2 ) { return name(); }
+  static std::string concreteName( T_ptr& t2 ) { return name(); }
 };

-------------------------------------------------------------------

Basically what I did was to remove the 'const' off of type T (or T_ptr in the
pointer case).  Given how TypeNameTraits<T>::concreteName(*p) in
Teuchos_[Array]RCP.hpp, it makes sense to remove the const.  However, I left
the const in the other full speicalizations since that makes the most sense
and the compiler does not complain about these.

This port is not finished yet since EpetraExt_MultiMpiComm.h still does not
compile but I am going to ask for some help with that one.