Changed line 519 from:
    int linelen = 512;
    char line[linelen];

to:

    int linelen = 512;
    char line[512];

compiling with g++ (version 3.3 or 3.4) fails if the -pedantic flag is enabled because the above line is not ISO standard.  The error was:

../../../../../packages/epetraext/test/MatrixMatrix/cxx_main.cpp:519: error: ISO C++ forbids variable-size array `line'