MueLu: SchwarzSmoother: Removed code that duplicates Ifpack2::Factory.
MueLu already calls Ifpack2::Factory elsewhere to make Ifpack2 widgets.
Thus, it's silly for MueLu to replicate the insides of Ifpack2::Factory.
I changed it just to call Ifpack2::Factory directly.

btw, MueLu has build errors if you enable Amesos:

.../Trilinos/packages/muelu/test/unit_tests/Smoothers/AmesosSmoother.cpp:63:9:
error: use of undeclared identifier 'testApplyNoSetup';
did you mean 'TestHelpers::Smoothers::testApplyNoSetup'?

        testApplyNoSetup(AmesosSmoother(), out, success);
        ^~~~~~~~~~~~~~~~
        TestHelpers::Smoothers::testApplyNoSetup

.../Trilinos/packages/muelu/test/unit_tests/Smoothers/MueLu_TestHelpersSmoothers.hpp:68:12:
note: 'TestHelpers::Smoothers::testApplyNoSetup' declared here

      void testApplyNoSetup(SmootherPrototype const & smoother, Teuchos::FancyOStream & out, bool & success);
           ^
.../Trilinos/packages/muelu/test/unit_tests/Smoothers/AmesosSmoother.cpp:74:9:
error: use of undeclared identifier 'testDirectSolver';
did you mean 'TestHelpers::Smoothers::testDirectSolver'?

        testDirectSolver(*smoother, out, success);
        ^~~~~~~~~~~~~~~~
        TestHelpers::Smoothers::testDirectSolver

Build/Test Cases Summary
Enabled Packages: MueLu
Disabled Packages: MOOCHO,Rythmos,Anasazi,OptiPack,Moertel,FEI,NOX,RBGen,Amesos
Enabled all Forward Packages
0) MPI_DEBUG => Test case MPI_DEBUG was not run! => Does not affect push readiness! (-1.00 min)
1) SERIAL_RELEASE => Test case SERIAL_RELEASE was not run! => Does not affect push readiness! (-1.00 min)
2) MPI_DEBUG_SS => FAILED: no tests run (0.19 min)
WARNING: Forced the push!