MueLu: improve EasyParameterListInterpreter msg
Improving exception handling and message.

Previously, if a parameter had the wrong type, an exception with a ambiguous message would be thrown:

  terminate called after throwing an instance of 'Teuchos::Exceptions::InvalidParameterType'
    what():  Error!  An attempt was made to access parameter "sa: damping factor" of type "int"
    in the parameter (sub)list "ANONYMOUS" using the incorrect type "double"!

Now the exception is caught, and a more helpful message is printed:

terminate called after throwing an instance of
'Teuchos::Exceptions::InvalidParameterType'
  what(): muelu/src/Interface/MueLu_EasyParameterListInterpreter_def.hpp:423:
  Throw number = 2
  Throw test that evaluated to true: true
  Error: parameter "sa: damping factor" must be of type double

Build/Test Cases Summary
Enabled Packages: MueLu
Enabled all Forward Packages
0) MPI_DEBUG => Skipped configure, build, test due to no enabled packages! => Does not affect push readiness! (-1.00 min)
1) SERIAL_RELEASE => Skipped configure, build, test due to no enabled packages! => Does not affect push readiness! (-1.00 min)
2) MPI_SS_DEBUG => passed: passed=143,notpassed=0 (12.59 min)
3) SERIAL_SS_DEBUG => passed: passed=106,notpassed=0 (15.12 min)